<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<link href="css/blog.css" rel="stylesheet" type="text/css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<style type = "text/css">
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }

        .container {
            padding-right: 15px;
            padding-left: 15px;
            padding-bottom: 15px;
            margin-right: auto;
            margin-left: auto;
        }

        a{
            text-decoration: none;
        }

        @media (min-width: 1200px) {
            .container {
                width: 1170px
            }
        }
    }
</style>
</head>

<body>
<div>
    <div class="container">
        <header class="blog-header py-1">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="d-flex justify-content-center">
                    <a class="blog-header-logo text-dark" href="#">United Internet</a>
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <a class="text-muted" href="#" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
                </a>
                <a class="btn btn-sm btn-outline-secondary" href="signin.ftlh">Sign up</a>
            </div>
        </header>

        <div class="nav-scroller">
            <nav class="d-flex justify-content-start">
                <a class="p-2 text-muted" href="articles.ftlh">Статьи</a>
                <a class="p-2 text-muted" href="videos.ftlh">Видео</a>
                <a class="p-2 text-muted" href="#">Форум</a>
                <a class="p-2 text-muted" href="#">Энциклопедия</a>

            </nav>
        </div>

<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <div class="col">
        <h1 class="display-6 font-italic">Видео</h1>
    </div>

    <div class="col">
        <div class="clearfix">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/rfexQ2QyD4I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></iframe>
        </div>
    </div>
</div>
        <br>

<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
<div class="col">
    <div class="clearfix">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/k_0BAtyaDio" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></iframe></iframe>
    </div>
</div>
</div>
        <br>

<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
<div class="col">
    <div class="clearfix">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/vobsAhMBPVw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></iframe></iframe>
    </div>
</div>
</div>
        <br>

<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
<div class="col">
    <div class="clearfix">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/TNQsmPf24go" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></iframe></iframe>
    </div>
</div>
</div>
        <br>

<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
<div class="col">
    <div class="clearfix">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/7n3zldzvzTc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></iframe></iframe>
    </div>
</div>
</div>
    </div>
</div>
</body>
</html>


